[package]
name = "blobular"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
flate2 = { version = "1.0.28", features = ["zlib"] }
sha1 = "0.10.6"
